kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"        
      port: 8081            
      # Port accessible inside cluster
      targetPort: 80        
      # Port to forward to inside the pod - container port
      nodePort: 30002       
      # Port accessible outside cluster
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          ports:
            - containerPort: 80