kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"        
      port: 8081            
      # Port accessible inside cluster
      targetPort: 80        
      # Port to forward to inside the pod - container port
      nodePort: 30002       
      # Port accessible outside cluster
  type: LoadBalancer

---
apiVersion: apps/v1 
# Which version of the Kubernetes API you’re using to create this object
# for versions before 1.9.0 use apps/v1beta2
kind: Deployment
#What kind of object you want to create
metadata:
#Data that helps uniquely identify the object, including a name string, UID, and optional namespace
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  # tells deployment to run 2 pods matching the template
  template:
  # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          ports:
            - containerPort: 80
